set fileencodings=ucs-bom,utf-8,cp936,big5,euc-jp,euc-kr,gb18030,latin1
set tabstop=2       
set shiftwidth=2    
set expandtab       
set smarttab      
set showcmd   
set number   
set showmatch 
set hlsearch 
set incsearch 
set ignorecase 
set smartcase  
set backspace=2  
set autoindent  
set textwidth=79 
set formatoptions=c,q,r,t 
set ruler     
set background=dark
set mouse=a    
filetype plugin indent on
syntax on
